// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// cropDao is the data access object for the table crop.
// You can define custom methods on it to extend its functionality as needed.
type cropDao struct {
	*internal.CropDao
}

var (
	// Crop is a globally accessible object for table crop operations.
	Crop = cropDao{internal.NewCropDao()}
)

// Add your custom methods and functionality below.
