// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// fieldCropDao is the data access object for the table field_crop.
// You can define custom methods on it to extend its functionality as needed.
type fieldCropDao struct {
	*internal.FieldCropDao
}

var (
	// FieldCrop is a globally accessible object for table field_crop operations.
	FieldCrop = fieldCropDao{internal.NewFieldCropDao()}
)

// Add your custom methods and functionality below.
