// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// fieldCropMaterialDao is the data access object for the table field_crop_material.
// You can define custom methods on it to extend its functionality as needed.
type fieldCropMaterialDao struct {
	*internal.FieldCropMaterialDao
}

var (
	// FieldCropMaterial is a globally accessible object for table field_crop_material operations.
	FieldCropMaterial = fieldCropMaterialDao{internal.NewFieldCropMaterialDao()}
)

// Add your custom methods and functionality below.
