// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// fieldDao is the data access object for the table field.
// You can define custom methods on it to extend its functionality as needed.
type fieldDao struct {
	*internal.FieldDao
}

var (
	// Field is a globally accessible object for table field operations.
	Field = fieldDao{internal.NewFieldDao()}
)

// Add your custom methods and functionality below.
