// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// materialDao is the data access object for the table material.
// You can define custom methods on it to extend its functionality as needed.
type materialDao struct {
	*internal.MaterialDao
}

var (
	// Material is a globally accessible object for table material operations.
	Material = materialDao{internal.NewMaterialDao()}
)

// Add your custom methods and functionality below.
