// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// pestRecordDao is the data access object for the table pest_record.
// You can define custom methods on it to extend its functionality as needed.
type pestRecordDao struct {
	*internal.PestRecordDao
}

var (
	// PestRecord is a globally accessible object for table pest_record operations.
	PestRecord = pestRecordDao{internal.NewPestRecordDao()}
)

// Add your custom methods and functionality below.
