# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:123456@tcp(127.0.0.1:3306)/edu"
        tables:          "pest_record"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/system"